name: xml_map_converter
description: XML to Dart map converter and vice versa
version: 1.0.0
homepage: https://github.com/andyduke/xml_map_converter/tree/master/package
repository: https://github.com/andyduke/xml_map_converter
issues: https://github.com/andyduke/xml_map_converter/issues

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  xmlstream: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
